/*
 *
 *
 *
 *
 *
 *         WARNING: Editing this file may prevent future updates via schematics.
 *                  To maintain easy upgradability, do not edit this file.
 *
 *
 *
 *
 *
 */

import {
  HTTP_INTERCEPTORS,
  HttpEvent,
  HttpHandler,
  HttpRequest,
} from '@angular/common/http';
import { Observable } from 'rxjs';

export const mockUserContextCookieInterceptor = {
  provide: HTTP_INTERCEPTORS,
  useValue: {
    intercept(
      req: HttpRequest<any>,
      next: HttpHandler
    ): Observable<HttpEvent<any>> {
      const setContextEndpoint =
        'access-control/client-api/v2/accessgroups/usercontext';
      const enabled = localStorage.getItem('enableMocks') === 'true';
      if (
        enabled &&
        req.url.endsWith(setContextEndpoint) &&
        req.method === 'POST'
      ) {
        document.cookie = 'USER_CONTEXT=fake-user-context-cookie';
      }
      return next.handle(req);
    },
  },
  multi: true,
};
