/*
 *
 *
 *
 *
 *
 *         WARNING: Editing this file may prevent future updates via schematics.
 *                  To maintain easy upgradability, do not edit this file.
 *
 *
 *
 *
 *
 */
import { NgModule } from '@angular/core';
import { EmployeeWorkspaceCustomerSupportModule } from '@backbase/employee-workspace-customer-support';
import { CustomerSupportWorkspaceRoutesModule } from './customer-support-workspace-routes.module';
import { customerSupportWorkspaceModuleImports } from './customer-support-workspace-module-imports';
import { RouterModule } from '@angular/router';
import { CustomerSupportWorkspaceNavigationComponent } from './navigation/customer-support-workspace-navigation.component';
import { Sidebar } from '@backbase/employee-web-app-layout';

export const sidebar = new Sidebar(CustomerSupportWorkspaceNavigationComponent);

@NgModule({
  imports: [
    EmployeeWorkspaceCustomerSupportModule,
    CustomerSupportWorkspaceRoutesModule,
    RouterModule,
    ...customerSupportWorkspaceModuleImports,
  ],
  declarations: [CustomerSupportWorkspaceNavigationComponent],
  entryComponents: [CustomerSupportWorkspaceNavigationComponent],
  providers: [{ provide: Sidebar, useValue: sidebar }],
})
export class CustomerSupportWorkspaceLoaderModule {}
